stages:
  - build
  - test
build the website:
  stage: build
  image: node
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./build

Test the app:
  stage: test
  image: node
  script:
  - npm install
  - npm test

