image: node

stages:
  - build
  - test
  - deploy
build the website:
  stage: build
  script:
    - npm install
    - npm run build
    - cd build
    - cp index.html 200.html
  artifacts:
    paths:
      - ./build

Test the app:
  stage: test
  script:
  - npm install
  - npm test

Deploy to surge:
    stage: deploy
    script:
      - npm install --global surge
      - surge --project ./build --domain https://akpostherapie.surge.sh

